INSERT INTO `institution` VALUES (127, 'atmajayajakarta', 'Universitas Katolik Indonesia Atma Jaya Jakarta', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (128, 'azzahra', 'Universitas Azzahra', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (129, 'borobudur', 'Universitas Borobudur', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (130, 'haluoleo', 'UNIVERSITAS HALUOLEO', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (131, 'iainsas', 'IAIN SUNAN AMPEL SURABAYA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (132, 'ibii', 'Institut Bisnis dan Informatika Indonesia (IBII)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (133, 'ibn', 'Institut Bisnis Nusantara (IBN)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (134, 'iisip', 'Institut Ilmu Sosial dan Ilmu Politik Jakarta (IISIP)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (135, 'ikj', 'Institut Kesenian Jakarta (IKJ)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (136, 'imt', 'Institut Manajemen Telkom', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (137, 'ipb', 'INSTITUT PERTANIAN BOGOR', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (138, 'ista', 'Institut Sains dan Teknologi Al-Kamal (ISTA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (139, 'istn', 'Institut Sains dan Teknologi Nasional (ISTN)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (140, 'itbk', 'Institut Sains dan Teknologi Kalbe (ITBK)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (141, 'itb', 'INSTITUT TEKNOLOGI BANDUNG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (142, 'itbu', 'Institut Teknologi Budi Utomo (ITBU)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (143, 'ithb', 'Institut Teknologi Harapan Bangsa', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (144, 'iti', 'Institut Teknologi Indonesia (ITI)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (145, 'itn', 'Institut Teknologi Nasional', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (146, 'itsb', 'Institut Teknologi Sains Bandung', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (147, 'itsn', 'INSTITUT TEKNOLOGI SEPULUH NOPEMBER', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (148, 'itt', 'Institut Teknologi Telkom', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (149, 'jayabaya', 'Universitas Jayabaya', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (150, 'kejuangan45jakarta', 'Universitas Kejuangan 45 Jakarta', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (151, 'khairun', 'UNIVERSITAS KHAIRUN', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (152, 'other', 'other', 'd1,d2,d3,tk,sd,smp,sma,s1,s2,s3', NULL, NULL);
INSERT INTO `institution` VALUES (153, 'paramadina', 'Universitas Paramadina', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (154, 'perbanas', 'Institut Keuangan Perbankan dan Informatika Asia Perbanas (AFBI Institute Perbanas)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (155, 'trisakti', 'Universitas Trisakti', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (156, 'uai', 'Universitas Al Azhar Indonesia (UAI)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (157, 'ub', 'Universitas Bakrie (UB) ', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (158, 'ubb', 'UNIVERSITAS BANGKA BELITUNG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (159, 'ubharajaya', 'Universitas Bhayangkara Jaya (UBHARA JAYA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (160, 'ubinus', 'Universitas Bina Nusantara (UBINUS)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (161, 'ubk', 'Universitas Bung Karno (UBK)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (162, 'ubl', 'Universitas Budi Luhur (UBL)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (163, 'ubm', 'Universitas Bunda Mulia (UBM)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (164, 'ubt', 'UNIVERSITAS BORNEO TARAKAN', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (165, 'ugm', 'UNIVERSITAS GADJAH MADA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (166, 'ug', 'Universitas Gunadarma (UG)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (167, 'uhamka', 'Universitas Muhammadiyah Prof. Dr. HAMKA (UHAMKA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (168, 'ui', 'UNIVERSITAS INDONESIA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (169, 'uic', 'Universitas Ibnu Chaldun (UIC)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (170, 'uid', 'Universitas Islam Jakarta (UID)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (171, 'uieu', 'Universitas Indonusa Esa Unggul', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (172, 'uinmim', 'UIN MALIK IBRAHIM MALANG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (173, 'uinsam', 'UIN SULTAN ALAUDDIN MAKASSAR', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (174, 'uinsgdb', 'UIN SUNAN GUNUNG DJATI BANDUNG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (175, 'uinshj', 'UIN SYARIF HIDAYATULLAH JAKARTA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (176, 'uinsky', 'UIN SUNAN KALIJAGA YOGYAKARTA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (177, 'uinsskr', 'UIN SULTAN SYARIF KASIM RIAU', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (178, 'uki', 'Universitas Kristen Indonesia (UKI)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (179, 'ukrida', 'Universitas Kristen Krida Wacana (UKRIDA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (180, 'ukris', 'Universitas Krisnadwipayana (UKRIS)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (181, 'umb', 'Universitas Mercu Buana (UMB)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (182, 'umj', 'Universitas Muhammadiyah Jakarta (UMJ)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (183, 'umm', 'UNIVERSITAS MUSAMUS MERAUKE', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (184, 'umn', 'Universitas Multimedia Nusantara (UMN)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (185, 'umrah', 'UNIVERSITAS MARITIM RAJA ALI HAJI', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (186, 'umt', 'Universitas Mpu Tantular (UMT)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (187, 'unair', 'UNIVERSITAS AIRLANGGA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (188, 'unand', 'UNIVERSITAS ANDALAS', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (189, 'unas', 'Universitas Nasional (UNAS)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (190, 'uncen', 'UNIVERSITAS CENDERAWASIH', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (191, 'uncendana', 'UNIVERSITAS NUSA CENDANA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (192, 'undip', 'UNIVERSITAS DIPONEGORO', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (193, 'unej', 'UNIVERSITAS JEMBER', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (194, 'ungorontalo', 'UNIVERSITAS NEGERI GORONTALO', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (195, 'unhas', 'UNIVERSITAS HASANUDDIN', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (196, 'unias', 'Universitas Islam As-Syafiiyah', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (197, 'uniat', 'Universitas Islam Attahiriyah (UNIAT)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (198, 'unib', 'UNIVERSITAS BENGKULU', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (199, 'unibraw', 'UNIVERSITAS BRAWIJAYA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (200, 'unija', 'Universitas Jakarta (UNIJA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (201, 'unila', 'UNIVERSITAS LAMPUNG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (202, 'unima', 'UNIVERSITAS MALIKUSSALEH', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (203, 'unindra', 'Universitas Indraprasta PGRI (UNINDRA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (204, 'uniraya', 'UNIVERSITAS PALANGKARAYA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (205, 'unj', 'UNIVERSITAS NEGERI JAKARTA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (206, 'unja', 'UNIVERSITAS JAMBI', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (207, 'unlam', 'UNIVERSITAS LAMBUNG MANGKURAT', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (208, 'unmakassar', 'UNIVERSITAS NEGERI MAKASSAR', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (209, 'unmalang', 'UNIVERSITAS NEGERI MALANG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (210, 'unmanado', 'UNIVERSITAS NEGERI MANADO', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (211, 'unmedan', 'UNIVERSITAS NEGERI MEDAN', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (212, 'unmul', 'UNIVERSITAS MULAWARMAN', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (213, 'unpadang', 'UNIVERSITAS NEGERI PADANG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (214, 'unpad', 'UNIVERSITAS PADJADJARAN', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (215, 'unpapua', 'UNIVERSITAS NEGERI PAPUA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (216, 'unpati', 'Universitas Surapati', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (217, 'unpatti', 'UNIVERSITAS PATTIMURA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (218, 'unram', 'UNIVERSITAS MATARAM', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (219, 'uns', 'UNIVERSITAS SEBELAS MARET', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (220, 'unsada', 'Universitas Darma Persada (UNSADA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (221, 'unsemarang', 'UNIVERSITAS NEGERI SEMARANG', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (222, 'unsoed', 'UNIVERSITAS JENDERAL SOEDIRMAN', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (223, 'unsrat', 'UNIVERSITAS SAM RATULANGI', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (224, 'unsri', 'UNIVERSITAS SRIWIJAYA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (225, 'unsurabaya', 'UNIVERSITAS NEGERI SURABAYA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (226, 'unsurya', 'Universitas Suryadarma (UNSURYA)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (227, 'unsyiah', 'UNIVERSITAS SYIAH KUALA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (228, 'untad', 'UNIVERSITAS TADULAKO', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (229, 'untag', 'Universitas 17 Agustus 1945 (UNTAG)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (230, 'untan', 'UNIVERSITAS TANJUNGPURA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (231, 'untar', 'Universitas Tarumanagara (UNTAR)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (232, 'untirta', 'UNIVERSITAS SULTAN AGENG TIRTAYASA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (233, 'unud', 'UNIVERSITAS UDAYANA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (234, 'unyogya', 'UNIVERSITAS NEGERI YOGYAKARTA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (235, 'up', 'Universitas Pancasila (UP)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (236, 'updm', 'Universitas Prof Dr Moestopo (Beragama) (UPDM)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (237, 'upg', 'UNIVERSITAS PENDIDIKAN GANESHA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (238, 'uph', 'Universitas Pelita Harapan (UPH)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (239, 'upi', 'UNIVERSITAS PENDIDIKAN INDONESIA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (240, 'upiyai', 'Universitas Persada Indonesia Yayasan Administrasi Indonesia (UPI Y.A.I)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (241, 'upnvj', 'UPN Veteran Jakarta (UPNVJ)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (242, 'uriau', 'UNIVERSITAS RIAU', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (243, 'urindo', 'Universitas Respati Indonesia (URINDO)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (244, 'usahid', 'Universitas Sahid (USAHID)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (245, 'usg', 'Universitas Satyagama (USG)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (246, 'usni', 'Universitas Satya Negara Indonesia (USNI)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (247, 'usu', 'UNIVERSITAS SUMATERA UTARA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (248, 'utamajagakarsa', 'Universitas Tama Jagakarsa', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (249, 'utirta-ibek', 'Universitas Timbul Nusantara (UTIRTA-IBEK)', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (250, 'utm', 'UNIVERSITAS TRUNOJOYO MADURA', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (251, 'uwi', 'Universitas Wiraswasta Indonesia', 's1,s2', NULL, NULL);
INSERT INTO `institution` VALUES (252, 'uyarsi', 'Universitas YARSI', 's1,s2', NULL, NULL);
