INSERT INTO `reference` VALUES (3, NULL, 'gender', 'Male', 'male');
INSERT INTO `reference` VALUES (4, NULL, 'gender', 'Female', 'female');
INSERT INTO `reference` VALUES (5, NULL, 'religion', 'Other', 'other');
INSERT INTO `reference` VALUES (6, NULL, 'religion', 'Islam', 'islam');
INSERT INTO `reference` VALUES (7, NULL, 'religion', 'Hindu', 'hindu');
INSERT INTO `reference` VALUES (8, NULL, 'religion', 'Protestant', 'protestant');
INSERT INTO `reference` VALUES (9, NULL, 'religion', 'Catholic', 'catholic');
INSERT INTO `reference` VALUES (10, NULL, 'religion', 'Buddha', 'buddha');
INSERT INTO `reference` VALUES (11, NULL, 'religion', 'Confucius', 'confucius');
INSERT INTO `reference` VALUES (12, NULL, 'marriage_status', 'Married', 'married');
INSERT INTO `reference` VALUES (13, NULL, 'marriage_status', 'Single', 'single');
INSERT INTO `reference` VALUES (14, NULL, 'marriage_status', 'Separated', 'separated');
INSERT INTO `reference` VALUES (15, NULL, 'marriage_status', 'Divorced', 'divorced');
INSERT INTO `reference` VALUES (16, NULL, 'marriage_status', 'Widowed', 'widowed');
INSERT INTO `reference` VALUES (17, NULL, 'marriage_status', 'Other', 'other');
INSERT INTO `reference` VALUES (18, NULL, 'user_status', 'unvalidated', 'unvalidated');
INSERT INTO `reference` VALUES (19, NULL, 'user_status', 'validated', 'validated');
INSERT INTO `reference` VALUES (20, NULL, 'user_status', 'profile', 'profile');
INSERT INTO `reference` VALUES (21, NULL, 'user_status', 'profile,photo', 'profile,photo');
INSERT INTO `reference` VALUES (22, NULL, 'academic_level', 'tk', 'kindergarten');
INSERT INTO `reference` VALUES (23, NULL, 'academic_level', 'sd', 'elementary');
INSERT INTO `reference` VALUES (24, NULL, 'academic_level', 'smp', 'junior high');
INSERT INTO `reference` VALUES (25, NULL, 'academic_level', 'sma', 'high school');
INSERT INTO `reference` VALUES (26, NULL, 'academic_level', 's1', 'bachelor');
INSERT INTO `reference` VALUES (27, NULL, 'academic_level', 's2', 'master');
INSERT INTO `reference` VALUES (28, NULL, 'academic_level', 's3', 'doctorate');
INSERT INTO `reference` VALUES (29, NULL, 'contact_type', 'home', 'home');
INSERT INTO `reference` VALUES (30, NULL, 'contact_type', 'work', 'work');
INSERT INTO `reference` VALUES (31, NULL, 'contact_type', 'mobile', 'mobile');
INSERT INTO `reference` VALUES (32, NULL, 'contact_type', 'other', 'other');
INSERT INTO `reference` VALUES (33, NULL, 'relation_type', 'sibling', 'sibling');
INSERT INTO `reference` VALUES (34, NULL, 'relation_type', 'parent', 'parent');
INSERT INTO `reference` VALUES (35, NULL, 'relation_type', 'children', 'children');
INSERT INTO `reference` VALUES (36, NULL, 'relation_type', 'other', 'other');
INSERT INTO `reference` VALUES (37, NULL, 'ethnicity', 'other', 'other');
INSERT INTO `reference` VALUES (38, NULL, 'ethnicity', 'batak', 'batak');
INSERT INTO `reference` VALUES (39, NULL, 'ethnicity', 'jawa', 'jawa');
INSERT INTO `reference` VALUES (40, NULL, 'ethnicity', 'sunda', 'sunda');
INSERT INTO `reference` VALUES (41, NULL, 'ethnicity', 'chinese', 'chinese');
INSERT INTO `reference` VALUES (48, NULL, 'place', 'other', 'other');
INSERT INTO `reference` VALUES (49, NULL, 'place', 'jakarta,dki', 'Jakarta, DKI');
INSERT INTO `reference` VALUES (50, NULL, 'place', 'bandung,jabar', 'Bandung, Jabar');
INSERT INTO `reference` VALUES (51, NULL, 'industry', 'other', 'other');
INSERT INTO `reference` VALUES (52, NULL, 'industry', 'computer technology', 'computer technology');
INSERT INTO `reference` VALUES (53, NULL, 'industry', 'social service', 'social service');
INSERT INTO `reference` VALUES (56, NULL, 'nationality', 'indonesia', 'indonesia');
INSERT INTO `reference` VALUES (57, NULL, 'nationality', 'other', 'other');
INSERT INTO `reference` VALUES (58, NULL, 'country', 'indonesia', 'indonesia');
INSERT INTO `reference` VALUES (59, NULL, 'country', 'other', 'other');
INSERT INTO `reference` VALUES (66, NULL, 'academic_level', 'n/a', 'n/a');
INSERT INTO `reference` VALUES (67, NULL, 'academic_level', 'd1', 'd1');
INSERT INTO `reference` VALUES (68, NULL, 'academic_level', 'd2', 'd2');
INSERT INTO `reference` VALUES (69, NULL, 'academic_level', 'd3', 'd3');
INSERT INTO `reference` VALUES (70, NULL, 'relation_type', 'wife', 'wife');
INSERT INTO `reference` VALUES (71, NULL, 'relation_type', 'husband', 'husband');
INSERT INTO `reference` VALUES (72, NULL, 'ethnicity', 'aceh', 'aceh');
INSERT INTO `reference` VALUES (73, NULL, 'ethnicity', 'ambon', 'ambon');
INSERT INTO `reference` VALUES (74, NULL, 'ethnicity', 'bali', 'bali');
INSERT INTO `reference` VALUES (75, NULL, 'ethnicity', 'bugis', 'bugis');
INSERT INTO `reference` VALUES (76, NULL, 'ethnicity', 'caucasian', 'caucasian');
INSERT INTO `reference` VALUES (77, NULL, 'ethnicity', 'dayak', 'dayak');
INSERT INTO `reference` VALUES (78, NULL, 'ethnicity', 'eurasian', 'eurasian');
INSERT INTO `reference` VALUES (79, NULL, 'ethnicity', 'india', 'india');
INSERT INTO `reference` VALUES (80, NULL, 'ethnicity', 'makasar', 'makasar');
INSERT INTO `reference` VALUES (81, NULL, 'ethnicity', 'manado', 'manado');
INSERT INTO `reference` VALUES (82, NULL, 'ethnicity', 'melayu', 'melayu');
INSERT INTO `reference` VALUES (83, NULL, 'ethnicity', 'middle-eastern', 'middle-eastern');
INSERT INTO `reference` VALUES (84, NULL, 'ethnicity', 'padang', 'padang');
INSERT INTO `reference` VALUES (85, NULL, 'ethnicity', 'tapanuli', 'tapanuli');
INSERT INTO `reference` VALUES (86, NULL, 'ethnicity', 'timor', 'timor');
INSERT INTO `reference` VALUES (87, NULL, 'major', 'ADMINISTRASI PENDIDIKAN', 'ADMINISTRASI PENDIDIKAN');
INSERT INTO `reference` VALUES (88, NULL, 'major', 'Agribisnis', 'Agribisnis');
INSERT INTO `reference` VALUES (89, NULL, 'major', 'Agronomi ', 'Agronomi ');
INSERT INTO `reference` VALUES (90, NULL, 'major', 'Agroteknologi', 'Agroteknologi');
INSERT INTO `reference` VALUES (91, NULL, 'major', 'Akuntansi', 'Akuntansi');
INSERT INTO `reference` VALUES (93, NULL, 'major', 'Antropologi', 'Antropologi');
INSERT INTO `reference` VALUES (94, NULL, 'major', 'Arsitektur ', 'Arsitektur ');
INSERT INTO `reference` VALUES (95, NULL, 'major', 'BAHASA DAN SASTRA INDONESIA', 'BAHASA DAN SASTRA INDONESIA');
INSERT INTO `reference` VALUES (96, NULL, 'major', 'BAHASA DAN SASTRA INGGRIS', 'BAHASA DAN SASTRA INGGRIS');
INSERT INTO `reference` VALUES (97, NULL, 'major', 'BIMBINGAN DAN KONSELING', 'BIMBINGAN DAN KONSELING');
INSERT INTO `reference` VALUES (98, NULL, 'major', 'Biologi', 'Biologi');
INSERT INTO `reference` VALUES (100, NULL, 'major', 'Budidaya Perikanan ', 'Budidaya Perikanan ');
INSERT INTO `reference` VALUES (101, NULL, 'major', 'Ekonomi Pembangunan', 'Ekonomi Pembangunan');
INSERT INTO `reference` VALUES (102, NULL, 'major', 'Elektronika dan Instrumentasi ', 'Elektronika dan Instrumentasi ');
INSERT INTO `reference` VALUES (103, NULL, 'major', 'Farmasi', 'Farmasi');
INSERT INTO `reference` VALUES (104, NULL, 'major', 'Fisika', 'Fisika');
INSERT INTO `reference` VALUES (106, NULL, 'major', 'Fisika Teknik ', 'Fisika Teknik ');
INSERT INTO `reference` VALUES (107, NULL, 'major', 'Geofisika', 'Geofisika');
INSERT INTO `reference` VALUES (108, NULL, 'major', 'Geografi dan Ilmu Lingkungan', 'Geografi dan Ilmu Lingkungan');
INSERT INTO `reference` VALUES (109, NULL, 'major', 'Gizi Kesehatan ', 'Gizi Kesehatan ');
INSERT INTO `reference` VALUES (110, NULL, 'major', 'Ilmu Administrasi Bisnis', 'Ilmu Administrasi Bisnis');
INSERT INTO `reference` VALUES (111, NULL, 'major', 'Ilmu Administrasi Negara', 'Ilmu Administrasi Negara');
INSERT INTO `reference` VALUES (112, NULL, 'major', 'Ilmu dan Industri Peternakan ', 'Ilmu dan Industri Peternakan ');
INSERT INTO `reference` VALUES (113, NULL, 'major', 'Ilmu Ekonomi dan Keuangan Islam', 'Ilmu Ekonomi dan Keuangan Islam');
INSERT INTO `reference` VALUES (114, NULL, 'major', 'Ilmu Hama & Penyakit Tumbuhan', 'Ilmu Hama & Penyakit Tumbuhan');
INSERT INTO `reference` VALUES (115, NULL, 'major', 'Ilmu Hubungan Internasional', 'Ilmu Hubungan Internasional');
INSERT INTO `reference` VALUES (116, NULL, 'major', 'Ilmu Hukum', 'Ilmu Hukum');
INSERT INTO `reference` VALUES (117, NULL, 'major', 'Ilmu Kelautan', 'Ilmu Kelautan');
INSERT INTO `reference` VALUES (118, NULL, 'major', 'Ilmu Keolahragaan', 'Ilmu Keolahragaan');
INSERT INTO `reference` VALUES (119, NULL, 'major', 'Ilmu Keperawatan', 'Ilmu Keperawatan');
INSERT INTO `reference` VALUES (120, NULL, 'major', 'Ilmu Keperawatan Gigi', 'Ilmu Keperawatan Gigi');
INSERT INTO `reference` VALUES (121, NULL, 'major', 'Ilmu Kesejahteraan Sosial', 'Ilmu Kesejahteraan Sosial');
INSERT INTO `reference` VALUES (122, NULL, 'major', 'Ilmu Komputer', 'Ilmu Komputer');
INSERT INTO `reference` VALUES (123, NULL, 'major', 'Ilmu Komunikasi', 'Ilmu Komunikasi');
INSERT INTO `reference` VALUES (124, NULL, 'major', 'Ilmu Pemerintahan', 'Ilmu Pemerintahan');
INSERT INTO `reference` VALUES (125, NULL, 'major', 'Ilmu Pendidikan Agama Islam', 'Ilmu Pendidikan Agama Islam');
INSERT INTO `reference` VALUES (126, NULL, 'major', 'Ilmu Perpustakaan', 'Ilmu Perpustakaan');
INSERT INTO `reference` VALUES (127, NULL, 'major', 'Ilmu Peternakan', 'Ilmu Peternakan');
INSERT INTO `reference` VALUES (128, NULL, 'major', 'Ilmu Sejarah', 'Ilmu Sejarah');
INSERT INTO `reference` VALUES (129, NULL, 'major', 'Ilmu Tanah', 'Ilmu Tanah');
INSERT INTO `reference` VALUES (130, NULL, 'major', 'Kartografi dan Pengindraan Jauh ', 'Kartografi dan Pengindraan Jauh ');
INSERT INTO `reference` VALUES (131, NULL, 'major', 'Kedokteran Hewan ', 'Kedokteran Hewan ');
INSERT INTO `reference` VALUES (132, NULL, 'major', 'Kehutanan ', 'Kehutanan ');
INSERT INTO `reference` VALUES (133, NULL, 'major', 'Kimia', 'Kimia');
INSERT INTO `reference` VALUES (134, NULL, 'major', 'Manaj. Sumber Daya Perikanan', 'Manaj. Sumber Daya Perikanan');
INSERT INTO `reference` VALUES (135, NULL, 'major', 'Manajemen', 'Manajemen');
INSERT INTO `reference` VALUES (136, NULL, 'major', 'MANAJEMEN INDUSTRI KATERING', 'MANAJEMEN INDUSTRI KATERING');
INSERT INTO `reference` VALUES (137, NULL, 'major', 'MANAJEMEN PEMASARAN PARIWISATA', 'MANAJEMEN PEMASARAN PARIWISATA');
INSERT INTO `reference` VALUES (138, NULL, 'major', 'Matematika', 'Matematika');
INSERT INTO `reference` VALUES (139, NULL, 'major', 'Mikrobiologi Pertanian ', 'Mikrobiologi Pertanian ');
INSERT INTO `reference` VALUES (140, NULL, 'major', 'Pembangunan Wilayah', 'Pembangunan Wilayah');
INSERT INTO `reference` VALUES (141, NULL, 'major', 'Pemuliaan Tanaman', 'Pemuliaan Tanaman');
INSERT INTO `reference` VALUES (142, NULL, 'major', 'PENDIDIKAN AKUNTANSI', 'PENDIDIKAN AKUNTANSI');
INSERT INTO `reference` VALUES (143, NULL, 'major', 'PENDIDIKAN BAHASA ARAB', 'PENDIDIKAN BAHASA ARAB');
INSERT INTO `reference` VALUES (144, NULL, 'major', 'PENDIDIKAN BAHASA DAERAH', 'PENDIDIKAN BAHASA DAERAH');
INSERT INTO `reference` VALUES (145, NULL, 'major', 'PENDIDIKAN BAHASA INGGRIS', 'PENDIDIKAN BAHASA INGGRIS');
INSERT INTO `reference` VALUES (146, NULL, 'major', 'PENDIDIKAN BAHASA JEPANG', 'PENDIDIKAN BAHASA JEPANG');
INSERT INTO `reference` VALUES (147, NULL, 'major', 'PENDIDIKAN BAHASA JERMAN', 'PENDIDIKAN BAHASA JERMAN');
INSERT INTO `reference` VALUES (148, NULL, 'major', 'PENDIDIKAN BAHASA PERANCIS', 'PENDIDIKAN BAHASA PERANCIS');
INSERT INTO `reference` VALUES (149, NULL, 'major', 'PENDIDIKAN BHS DAN SASTRA INDONESIA', 'PENDIDIKAN BHS DAN SASTRA INDONESIA');
INSERT INTO `reference` VALUES (150, NULL, 'major', 'PENDIDIKAN BIOLOGI', 'PENDIDIKAN BIOLOGI');
INSERT INTO `reference` VALUES (151, NULL, 'major', 'Pendidikan Dokter', 'Pendidikan Dokter');
INSERT INTO `reference` VALUES (152, NULL, 'major', 'PENDIDIKAN EKONOMI', 'PENDIDIKAN EKONOMI');
INSERT INTO `reference` VALUES (153, NULL, 'major', 'PENDIDIKAN FISIKA', 'PENDIDIKAN FISIKA');
INSERT INTO `reference` VALUES (154, NULL, 'major', 'PENDIDIKAN GEOGRAFI', 'PENDIDIKAN GEOGRAFI');
INSERT INTO `reference` VALUES (155, NULL, 'major', 'PENDIDIKAN ILMU KOMPUTER', 'PENDIDIKAN ILMU KOMPUTER');
INSERT INTO `reference` VALUES (156, NULL, 'major', 'PENDIDIKAN IPS', 'PENDIDIKAN IPS');
INSERT INTO `reference` VALUES (157, NULL, 'major', 'PENDIDIKAN JASMANI, KESEHATAN DAN REKREASI', 'PENDIDIKAN JASMANI, KESEHATAN DAN REKREASI');
INSERT INTO `reference` VALUES (158, NULL, 'major', 'PENDIDIKAN KEPELATIHAN OLAHRAGA', 'PENDIDIKAN KEPELATIHAN OLAHRAGA');
INSERT INTO `reference` VALUES (159, NULL, 'major', 'PENDIDIKAN KESEJAHTERAAN KELUARGA', 'PENDIDIKAN KESEJAHTERAAN KELUARGA');
INSERT INTO `reference` VALUES (160, NULL, 'major', 'PENDIDIKAN KIMIA', 'PENDIDIKAN KIMIA');
INSERT INTO `reference` VALUES (161, NULL, 'major', 'PENDIDIKAN LUAR BIASA', 'PENDIDIKAN LUAR BIASA');
INSERT INTO `reference` VALUES (162, NULL, 'major', 'PENDIDIKAN LUAR SEKOLAH', 'PENDIDIKAN LUAR SEKOLAH');
INSERT INTO `reference` VALUES (163, NULL, 'major', 'PENDIDIKAN MANAJEMEN BISNIS', 'PENDIDIKAN MANAJEMEN BISNIS');
INSERT INTO `reference` VALUES (164, NULL, 'major', 'PENDIDIKAN MANAJEMEN PERKANTORAN', 'PENDIDIKAN MANAJEMEN PERKANTORAN');
INSERT INTO `reference` VALUES (165, NULL, 'major', 'PENDIDIKAN MATEMATIKA', 'PENDIDIKAN MATEMATIKA');
INSERT INTO `reference` VALUES (166, NULL, 'major', 'PENDIDIKAN RESORT DAN LEISURE', 'PENDIDIKAN RESORT DAN LEISURE');
INSERT INTO `reference` VALUES (167, NULL, 'major', 'PENDIDIKAN SEJARAH', 'PENDIDIKAN SEJARAH');
INSERT INTO `reference` VALUES (168, NULL, 'major', 'PENDIDIKAN SENI MUSIK', 'PENDIDIKAN SENI MUSIK');
INSERT INTO `reference` VALUES (169, NULL, 'major', 'PENDIDIKAN SENI RUPA DAN KERAJINAN', 'PENDIDIKAN SENI RUPA DAN KERAJINAN');
INSERT INTO `reference` VALUES (170, NULL, 'major', 'PENDIDIKAN SENI TARI', 'PENDIDIKAN SENI TARI');
INSERT INTO `reference` VALUES (171, NULL, 'major', 'PENDIDIKAN SOSILOGI', 'PENDIDIKAN SOSILOGI');
INSERT INTO `reference` VALUES (172, NULL, 'major', 'PENDIDIKAN TATA BOGA', 'PENDIDIKAN TATA BOGA');
INSERT INTO `reference` VALUES (173, NULL, 'major', 'PENDIDIKAN TATA BUSANA', 'PENDIDIKAN TATA BUSANA');
INSERT INTO `reference` VALUES (174, NULL, 'major', 'PENDIDIKAN TEKNIK ARSITEKTUR', 'PENDIDIKAN TEKNIK ARSITEKTUR');
INSERT INTO `reference` VALUES (175, NULL, 'major', 'PENDIDIKAN TEKNIK BANGUNAN', 'PENDIDIKAN TEKNIK BANGUNAN');
INSERT INTO `reference` VALUES (176, NULL, 'major', 'PENDIDIKAN TEKNIK ELEKTRO', 'PENDIDIKAN TEKNIK ELEKTRO');
INSERT INTO `reference` VALUES (177, NULL, 'major', 'Pendidikan Teknik Mesin', 'Pendidikan Teknik Mesin');
INSERT INTO `reference` VALUES (178, NULL, 'major', 'Pendidikan Teknologi Agro Industri', 'Pendidikan Teknologi Agro Industri');
INSERT INTO `reference` VALUES (179, NULL, 'major', 'Penyuluhan & Komunikasi Pertanian', 'Penyuluhan & Komunikasi Pertanian');
INSERT INTO `reference` VALUES (180, NULL, 'major', 'Perencanaan Wilayah dan Kota', 'Perencanaan Wilayah dan Kota');
INSERT INTO `reference` VALUES (181, NULL, 'major', 'Perikanan', 'Perikanan');
INSERT INTO `reference` VALUES (182, NULL, 'major', 'Perpustakaan dan Informasi', 'Perpustakaan dan Informasi');
INSERT INTO `reference` VALUES (183, NULL, 'major', 'PKN', 'PKN');
INSERT INTO `reference` VALUES (184, NULL, 'major', 'Psikologi', 'Psikologi');
INSERT INTO `reference` VALUES (185, NULL, 'major', 'Sastra Arab', 'Sastra Arab');
INSERT INTO `reference` VALUES (186, NULL, 'major', 'Sastra Indonesia', 'Sastra Indonesia');
INSERT INTO `reference` VALUES (187, NULL, 'major', 'Sastra Inggris', 'Sastra Inggris');
INSERT INTO `reference` VALUES (188, NULL, 'major', 'Sastra Jepang', 'Sastra Jepang');
INSERT INTO `reference` VALUES (189, NULL, 'major', 'Sastra Jerman', 'Sastra Jerman');
INSERT INTO `reference` VALUES (190, NULL, 'major', 'Sastra Perancis', 'Sastra Perancis');
INSERT INTO `reference` VALUES (191, NULL, 'major', 'Sastra Rusia', 'Sastra Rusia');
INSERT INTO `reference` VALUES (192, NULL, 'major', 'Sastra Sunda', 'Sastra Sunda');
INSERT INTO `reference` VALUES (193, NULL, 'major', 'Sos.ek. Pertanian (Agrobisnis)', 'Sos.ek. Pertanian (Agrobisnis)');
INSERT INTO `reference` VALUES (194, NULL, 'major', 'Sosiologi', 'Sosiologi');
INSERT INTO `reference` VALUES (195, NULL, 'major', 'Statistika', 'Statistika');
INSERT INTO `reference` VALUES (196, NULL, 'major', 'Teknik Arsitektur', 'Teknik Arsitektur');
INSERT INTO `reference` VALUES (197, NULL, 'major', 'Teknik Elektro', 'Teknik Elektro');
INSERT INTO `reference` VALUES (198, NULL, 'major', 'Teknik Geodesi', 'Teknik Geodesi');
INSERT INTO `reference` VALUES (199, NULL, 'major', 'Teknik Geologi', 'Teknik Geologi');
INSERT INTO `reference` VALUES (200, NULL, 'major', 'Teknik Industri ', 'Teknik Industri ');
INSERT INTO `reference` VALUES (201, NULL, 'major', 'Teknik Informatika', 'Teknik Informatika');
INSERT INTO `reference` VALUES (202, NULL, 'major', 'Teknik Kimia', 'Teknik Kimia');
INSERT INTO `reference` VALUES (203, NULL, 'major', 'Teknik Mesin', 'Teknik Mesin');
INSERT INTO `reference` VALUES (204, NULL, 'major', 'Teknik Nuklir', 'Teknik Nuklir');
INSERT INTO `reference` VALUES (205, NULL, 'major', 'Teknik Pertanian', 'Teknik Pertanian');
INSERT INTO `reference` VALUES (206, NULL, 'major', 'Teknik Sipil', 'Teknik Sipil');
INSERT INTO `reference` VALUES (207, NULL, 'major', 'Teknologi Hasil Perikanan', 'Teknologi Hasil Perikanan');
INSERT INTO `reference` VALUES (208, NULL, 'major', 'Teknologi Industri Pertanian', 'Teknologi Industri Pertanian');
INSERT INTO `reference` VALUES (209, NULL, 'major', 'Teknologi Informasi ', 'Teknologi Informasi ');
INSERT INTO `reference` VALUES (210, NULL, 'major', 'Teknologi Pangan', 'Teknologi Pangan');
INSERT INTO `reference` VALUES (211, NULL, 'major', 'Teknologi Pangan & Hasil Pertanian', 'Teknologi Pangan & Hasil Pertanian');
INSERT INTO `reference` VALUES (212, NULL, 'major', 'Teknologi Pendidikan', 'Teknologi Pendidikan');
INSERT INTO `reference` VALUES (213, NULL, 'major', 'other', 'other');
INSERT INTO `reference` VALUES (214, NULL, 'industry', 'Construction & industrial', 'Construction & industrial');
INSERT INTO `reference` VALUES (215, NULL, 'industry', 'Military', 'Militer');
INSERT INTO `reference` VALUES (216, NULL, 'industry', 'Health', 'Health');
INSERT INTO `reference` VALUES (217, NULL, 'province', 'DKI Jakarta', 'DKI Jakarta');
INSERT INTO `reference` VALUES (218, NULL, 'province', 'Jawa Barat', 'Jawa Barat');
INSERT INTO `reference` VALUES (219, NULL, 'province', 'Aceh ', 'Aceh ');
INSERT INTO `reference` VALUES (220, NULL, 'province', 'Bali', 'Bali');
INSERT INTO `reference` VALUES (221, NULL, 'province', 'Banten', 'Banten');
INSERT INTO `reference` VALUES (222, NULL, 'province', 'Bengkulu', 'Bengkulu');
INSERT INTO `reference` VALUES (223, NULL, 'province', 'Gorontalo', 'Gorontalo');
INSERT INTO `reference` VALUES (224, NULL, 'province', 'Jambi', 'Jambi');
INSERT INTO `reference` VALUES (225, NULL, 'province', 'Jawa Tengah', 'Jawa Tengah');
INSERT INTO `reference` VALUES (226, NULL, 'province', 'Jawa Timur', 'Jawa Timur');
INSERT INTO `reference` VALUES (227, NULL, 'province', 'Kalimantan Barat', 'Kalimantan Barat');
INSERT INTO `reference` VALUES (228, NULL, 'province', 'Kalimantan Selatan', 'Kalimantan Selatan');
INSERT INTO `reference` VALUES (229, NULL, 'province', 'Kalimantan Tengah', 'Kalimantan Tengah');
INSERT INTO `reference` VALUES (230, NULL, 'province', 'Kalimantan Timur', 'Kalimantan Timur');
INSERT INTO `reference` VALUES (231, NULL, 'province', 'Kalimantan Utara', 'Kalimantan Utara');
INSERT INTO `reference` VALUES (232, NULL, 'province', 'Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung');
INSERT INTO `reference` VALUES (233, NULL, 'province', 'Kepulauan Riau', 'Kepulauan Riau');
INSERT INTO `reference` VALUES (234, NULL, 'province', 'Lampung', 'Lampung');
INSERT INTO `reference` VALUES (235, NULL, 'province', 'Maluku', 'Maluku');
INSERT INTO `reference` VALUES (236, NULL, 'province', 'Maluku Utara', 'Maluku Utara');
INSERT INTO `reference` VALUES (237, NULL, 'province', 'Nusa Tenggara Barat', 'Nusa Tenggara Barat');
INSERT INTO `reference` VALUES (238, NULL, 'province', 'Nusa Tenggara Timur', 'Nusa Tenggara Timur');
INSERT INTO `reference` VALUES (239, NULL, 'province', 'Papua', 'Papua');
INSERT INTO `reference` VALUES (240, NULL, 'province', 'Papua Barat', 'Papua Barat');
INSERT INTO `reference` VALUES (241, NULL, 'province', 'Riau', 'Riau');
INSERT INTO `reference` VALUES (242, NULL, 'province', 'Sulawesi Barat', 'Sulawesi Barat');
INSERT INTO `reference` VALUES (243, NULL, 'province', 'Sulawesi Selatan', 'Sulawesi Selatan');
INSERT INTO `reference` VALUES (244, NULL, 'province', 'Sulawesi Tengah', 'Sulawesi Tengah');
INSERT INTO `reference` VALUES (245, NULL, 'province', 'Sulawsei Tenggara', 'Sulawsei Tenggara');
INSERT INTO `reference` VALUES (246, NULL, 'province', 'Sulawesi Utara', 'Sulawesi Utara');
INSERT INTO `reference` VALUES (247, NULL, 'province', 'Sumatera Barat', 'Sumatera Barat');
INSERT INTO `reference` VALUES (248, NULL, 'province', 'Sumatera Selatan', 'Sumatera Selatan');
INSERT INTO `reference` VALUES (249, NULL, 'province', 'Sumatera Utara', 'Sumatera Utara');
INSERT INTO `reference` VALUES (250, NULL, 'province', 'Yogyakarta', 'Yogyakarta');
INSERT INTO `reference` VALUES (251, NULL, 'province', 'Other', 'Other');
INSERT INTO `reference` VALUES (252, NULL, 'city', 'Ambon', 'Ambon');
INSERT INTO `reference` VALUES (253, NULL, 'city', 'Banda Aceh', 'Banda Aceh');
INSERT INTO `reference` VALUES (254, NULL, 'city', 'Bandar Lampung', 'Bandar Lampung');
INSERT INTO `reference` VALUES (255, NULL, 'city', 'Bandung', 'Bandung');
INSERT INTO `reference` VALUES (256, NULL, 'city', 'Banjarmasin', 'Banjarmasin');
INSERT INTO `reference` VALUES (257, NULL, 'city', 'Bengkulu', 'Bengkulu');
INSERT INTO `reference` VALUES (258, NULL, 'city', 'Dendapar', 'Dendapar');
INSERT INTO `reference` VALUES (259, NULL, 'city', 'Gorontalo', 'Gorontalo');
INSERT INTO `reference` VALUES (260, NULL, 'city', 'Jakarta Barat', 'Jakarta Barat');
INSERT INTO `reference` VALUES (261, NULL, 'city', 'Jakarta Timur', 'Jakarta Timur');
INSERT INTO `reference` VALUES (262, NULL, 'city', 'Jakarta Utara', 'Jakarta Utara');
INSERT INTO `reference` VALUES (263, NULL, 'city', 'Jakarta Selatan', 'Jakarta Selatan');
INSERT INTO `reference` VALUES (264, NULL, 'city', 'Jambi', 'Jambi');
INSERT INTO `reference` VALUES (265, NULL, 'city', 'Jayapura', 'Jayapura');
INSERT INTO `reference` VALUES (266, NULL, 'city', 'Kendari', 'Kendari');
INSERT INTO `reference` VALUES (267, NULL, 'city', 'Kupang', 'Kupang');
INSERT INTO `reference` VALUES (268, NULL, 'city', 'Makasar', 'Makasar');
INSERT INTO `reference` VALUES (269, NULL, 'city', 'Mamuju', 'Mamuju');
INSERT INTO `reference` VALUES (270, NULL, 'city', 'Manado', 'Manado');
INSERT INTO `reference` VALUES (271, NULL, 'city', 'Manokmari', 'Manokmari');
INSERT INTO `reference` VALUES (272, NULL, 'city', 'Mataram', 'Mataram');
INSERT INTO `reference` VALUES (273, NULL, 'city', 'Padang ', 'Padang ');
INSERT INTO `reference` VALUES (274, NULL, 'city', 'Palangkaraya', 'Palangkaraya');
INSERT INTO `reference` VALUES (275, NULL, 'city', 'Palembang', 'Palembang');
INSERT INTO `reference` VALUES (276, NULL, 'city', 'Palu', 'Palu');
INSERT INTO `reference` VALUES (277, NULL, 'city', 'Pangkjal Pinang', 'Pangkjal Pinang');
INSERT INTO `reference` VALUES (278, NULL, 'city', 'Pekanbaru', 'Pekanbaru');
INSERT INTO `reference` VALUES (279, NULL, 'city', 'Pontianak', 'Pontianak');
INSERT INTO `reference` VALUES (280, NULL, 'city', 'Samarinda', 'Samarinda');
INSERT INTO `reference` VALUES (281, NULL, 'city', 'Semarang', 'Semarang');
INSERT INTO `reference` VALUES (282, NULL, 'city', 'Serang', 'Serang');
INSERT INTO `reference` VALUES (283, NULL, 'city', 'Sofifi', 'Sofifi');
INSERT INTO `reference` VALUES (284, NULL, 'city', 'Surabaya', 'Surabaya');
INSERT INTO `reference` VALUES (285, NULL, 'city', 'Tanjung Pinang', 'Tanjung Pinang');
INSERT INTO `reference` VALUES (286, NULL, 'city', 'Tanjung Selor', 'Tanjung Selor');
INSERT INTO `reference` VALUES (287, NULL, 'city', 'Yogyakarta', 'Yogyakarta');
INSERT INTO `reference` VALUES (288, NULL, 'city', 'Other', 'Other');
